//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace EnableVue
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EV_DBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EV_DBEntities object using the connection string found in the 'EV_DBEntities' section of the application configuration file.
        /// </summary>
        public EV_DBEntities() : base("name=EV_DBEntities", "EV_DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EV_DBEntities object.
        /// </summary>
        public EV_DBEntities(string connectionString) : base(connectionString, "EV_DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EV_DBEntities object.
        /// </summary>
        public EV_DBEntities(EntityConnection connection) : base(connection, "EV_DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Batch> Batches
        {
            get
            {
                if ((_Batches == null))
                {
                    _Batches = base.CreateObjectSet<Batch>("Batches");
                }
                return _Batches;
            }
        }
        private ObjectSet<Batch> _Batches;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DetailedLOG> DetailedLOGs
        {
            get
            {
                if ((_DetailedLOGs == null))
                {
                    _DetailedLOGs = base.CreateObjectSet<DetailedLOG>("DetailedLOGs");
                }
                return _DetailedLOGs;
            }
        }
        private ObjectSet<DetailedLOG> _DetailedLOGs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FilesProcessed> FilesProcesseds
        {
            get
            {
                if ((_FilesProcesseds == null))
                {
                    _FilesProcesseds = base.CreateObjectSet<FilesProcessed>("FilesProcesseds");
                }
                return _FilesProcesseds;
            }
        }
        private ObjectSet<FilesProcessed> _FilesProcesseds;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ServiceState> ServiceStates
        {
            get
            {
                if ((_ServiceStates == null))
                {
                    _ServiceStates = base.CreateObjectSet<ServiceState>("ServiceStates");
                }
                return _ServiceStates;
            }
        }
        private ObjectSet<ServiceState> _ServiceStates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Setting> Settings
        {
            get
            {
                if ((_Settings == null))
                {
                    _Settings = base.CreateObjectSet<Setting>("Settings");
                }
                return _Settings;
            }
        }
        private ObjectSet<Setting> _Settings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SimpleLog> SimpleLogs
        {
            get
            {
                if ((_SimpleLogs == null))
                {
                    _SimpleLogs = base.CreateObjectSet<SimpleLog>("SimpleLogs");
                }
                return _SimpleLogs;
            }
        }
        private ObjectSet<SimpleLog> _SimpleLogs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserToken> UserTokens
        {
            get
            {
                if ((_UserTokens == null))
                {
                    _UserTokens = base.CreateObjectSet<UserToken>("UserTokens");
                }
                return _UserTokens;
            }
        }
        private ObjectSet<UserToken> _UserTokens;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Batches EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBatches(Batch batch)
        {
            base.AddObject("Batches", batch);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DetailedLOGs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDetailedLOGs(DetailedLOG detailedLOG)
        {
            base.AddObject("DetailedLOGs", detailedLOG);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FilesProcesseds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFilesProcesseds(FilesProcessed filesProcessed)
        {
            base.AddObject("FilesProcesseds", filesProcessed);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ServiceStates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToServiceStates(ServiceState serviceState)
        {
            base.AddObject("ServiceStates", serviceState);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Settings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSettings(Setting setting)
        {
            base.AddObject("Settings", setting);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SimpleLogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSimpleLogs(SimpleLog simpleLog)
        {
            base.AddObject("SimpleLogs", simpleLog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserTokens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserTokens(UserToken userToken)
        {
            base.AddObject("UserTokens", userToken);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EnableVue_DBModel", Name="Batch")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Batch : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Batch object.
        /// </summary>
        /// <param name="batch_Number">Initial value of the Batch_Number property.</param>
        public static Batch CreateBatch(global::System.Int32 batch_Number)
        {
            Batch batch = new Batch();
            batch.Batch_Number = batch_Number;
            return batch;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Batch_Number
        {
            get
            {
                return _Batch_Number;
            }
            set
            {
                if (_Batch_Number != value)
                {
                    OnBatch_NumberChanging(value);
                    ReportPropertyChanging("Batch_Number");
                    _Batch_Number = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Batch_Number");
                    OnBatch_NumberChanged();
                }
            }
        }
        private global::System.Int32 _Batch_Number;
        partial void OnBatch_NumberChanging(global::System.Int32 value);
        partial void OnBatch_NumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> startTime
        {
            get
            {
                return _startTime;
            }
            set
            {
                OnstartTimeChanging(value);
                ReportPropertyChanging("startTime");
                _startTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("startTime");
                OnstartTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _startTime;
        partial void OnstartTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnstartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> endTime
        {
            get
            {
                return _endTime;
            }
            set
            {
                OnendTimeChanging(value);
                ReportPropertyChanging("endTime");
                _endTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("endTime");
                OnendTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _endTime;
        partial void OnendTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnendTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> fileProcessed
        {
            get
            {
                return _fileProcessed;
            }
            set
            {
                OnfileProcessedChanging(value);
                ReportPropertyChanging("fileProcessed");
                _fileProcessed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fileProcessed");
                OnfileProcessedChanged();
            }
        }
        private Nullable<global::System.Int32> _fileProcessed;
        partial void OnfileProcessedChanging(Nullable<global::System.Int32> value);
        partial void OnfileProcessedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> filesFailed
        {
            get
            {
                return _filesFailed;
            }
            set
            {
                OnfilesFailedChanging(value);
                ReportPropertyChanging("filesFailed");
                _filesFailed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("filesFailed");
                OnfilesFailedChanged();
            }
        }
        private Nullable<global::System.Int32> _filesFailed;
        partial void OnfilesFailedChanging(Nullable<global::System.Int32> value);
        partial void OnfilesFailedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String folderpath
        {
            get
            {
                return _folderpath;
            }
            set
            {
                OnfolderpathChanging(value);
                ReportPropertyChanging("folderpath");
                _folderpath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("folderpath");
                OnfolderpathChanged();
            }
        }
        private global::System.String _folderpath;
        partial void OnfolderpathChanging(global::System.String value);
        partial void OnfolderpathChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EnableVue_DBModel", Name="DetailedLOG")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DetailedLOG : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DetailedLOG object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static DetailedLOG CreateDetailedLOG(global::System.Int32 id)
        {
            DetailedLOG detailedLOG = new DetailedLOG();
            detailedLOG.id = id;
            return detailedLOG;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Log
        {
            get
            {
                return _Log;
            }
            set
            {
                OnLogChanging(value);
                ReportPropertyChanging("Log");
                _Log = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Log");
                OnLogChanged();
            }
        }
        private global::System.String _Log;
        partial void OnLogChanging(global::System.String value);
        partial void OnLogChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> time
        {
            get
            {
                return _time;
            }
            set
            {
                OntimeChanging(value);
                ReportPropertyChanging("time");
                _time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("time");
                OntimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _time;
        partial void OntimeChanging(Nullable<global::System.DateTime> value);
        partial void OntimeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EnableVue_DBModel", Name="FilesProcessed")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FilesProcessed : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FilesProcessed object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="fileName">Initial value of the fileName property.</param>
        /// <param name="contentID">Initial value of the contentID property.</param>
        /// <param name="parsed">Initial value of the parsed property.</param>
        /// <param name="uploaded">Initial value of the uploaded property.</param>
        /// <param name="error">Initial value of the error property.</param>
        public static FilesProcessed CreateFilesProcessed(global::System.Int32 id, global::System.String fileName, global::System.String contentID, global::System.Boolean parsed, global::System.Boolean uploaded, global::System.Boolean error)
        {
            FilesProcessed filesProcessed = new FilesProcessed();
            filesProcessed.Id = id;
            filesProcessed.fileName = fileName;
            filesProcessed.contentID = contentID;
            filesProcessed.parsed = parsed;
            filesProcessed.uploaded = uploaded;
            filesProcessed.error = error;
            return filesProcessed;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String fileName
        {
            get
            {
                return _fileName;
            }
            set
            {
                OnfileNameChanging(value);
                ReportPropertyChanging("fileName");
                _fileName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("fileName");
                OnfileNameChanged();
            }
        }
        private global::System.String _fileName;
        partial void OnfileNameChanging(global::System.String value);
        partial void OnfileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String contentID
        {
            get
            {
                return _contentID;
            }
            set
            {
                OncontentIDChanging(value);
                ReportPropertyChanging("contentID");
                _contentID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("contentID");
                OncontentIDChanged();
            }
        }
        private global::System.String _contentID;
        partial void OncontentIDChanging(global::System.String value);
        partial void OncontentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean parsed
        {
            get
            {
                return _parsed;
            }
            set
            {
                OnparsedChanging(value);
                ReportPropertyChanging("parsed");
                _parsed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parsed");
                OnparsedChanged();
            }
        }
        private global::System.Boolean _parsed;
        partial void OnparsedChanging(global::System.Boolean value);
        partial void OnparsedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean uploaded
        {
            get
            {
                return _uploaded;
            }
            set
            {
                OnuploadedChanging(value);
                ReportPropertyChanging("uploaded");
                _uploaded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("uploaded");
                OnuploadedChanged();
            }
        }
        private global::System.Boolean _uploaded;
        partial void OnuploadedChanging(global::System.Boolean value);
        partial void OnuploadedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean error
        {
            get
            {
                return _error;
            }
            set
            {
                OnerrorChanging(value);
                ReportPropertyChanging("error");
                _error = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("error");
                OnerrorChanged();
            }
        }
        private global::System.Boolean _error;
        partial void OnerrorChanging(global::System.Boolean value);
        partial void OnerrorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String contentData1
        {
            get
            {
                return _contentData1;
            }
            set
            {
                OncontentData1Changing(value);
                ReportPropertyChanging("contentData1");
                _contentData1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("contentData1");
                OncontentData1Changed();
            }
        }
        private global::System.String _contentData1;
        partial void OncontentData1Changing(global::System.String value);
        partial void OncontentData1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String contentData2
        {
            get
            {
                return _contentData2;
            }
            set
            {
                OncontentData2Changing(value);
                ReportPropertyChanging("contentData2");
                _contentData2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("contentData2");
                OncontentData2Changed();
            }
        }
        private global::System.String _contentData2;
        partial void OncontentData2Changing(global::System.String value);
        partial void OncontentData2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String source
        {
            get
            {
                return _source;
            }
            set
            {
                OnsourceChanging(value);
                ReportPropertyChanging("source");
                _source = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("source");
                OnsourceChanged();
            }
        }
        private global::System.String _source;
        partial void OnsourceChanging(global::System.String value);
        partial void OnsourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String category
        {
            get
            {
                return _category;
            }
            set
            {
                OncategoryChanging(value);
                ReportPropertyChanging("category");
                _category = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("category");
                OncategoryChanged();
            }
        }
        private global::System.String _category;
        partial void OncategoryChanging(global::System.String value);
        partial void OncategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tag
        {
            get
            {
                return _tag;
            }
            set
            {
                OntagChanging(value);
                ReportPropertyChanging("tag");
                _tag = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tag");
                OntagChanged();
            }
        }
        private global::System.String _tag;
        partial void OntagChanging(global::System.String value);
        partial void OntagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String author
        {
            get
            {
                return _author;
            }
            set
            {
                OnauthorChanging(value);
                ReportPropertyChanging("author");
                _author = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("author");
                OnauthorChanged();
            }
        }
        private global::System.String _author;
        partial void OnauthorChanging(global::System.String value);
        partial void OnauthorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> batchNumber
        {
            get
            {
                return _batchNumber;
            }
            set
            {
                OnbatchNumberChanging(value);
                ReportPropertyChanging("batchNumber");
                _batchNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("batchNumber");
                OnbatchNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _batchNumber;
        partial void OnbatchNumberChanging(Nullable<global::System.Int32> value);
        partial void OnbatchNumberChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EnableVue_DBModel", Name="ServiceState")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ServiceState : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ServiceState object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="isrunning">Initial value of the isrunning property.</param>
        /// <param name="waitingforfiles">Initial value of the waitingforfiles property.</param>
        /// <param name="processignbatch">Initial value of the processignbatch property.</param>
        /// <param name="batchId">Initial value of the batchId property.</param>
        /// <param name="fileid">Initial value of the fileid property.</param>
        public static ServiceState CreateServiceState(global::System.Int32 id, global::System.Boolean isrunning, global::System.Boolean waitingforfiles, global::System.Boolean processignbatch, global::System.Int32 batchId, global::System.Int32 fileid)
        {
            ServiceState serviceState = new ServiceState();
            serviceState.Id = id;
            serviceState.isrunning = isrunning;
            serviceState.waitingforfiles = waitingforfiles;
            serviceState.processignbatch = processignbatch;
            serviceState.batchId = batchId;
            serviceState.fileid = fileid;
            return serviceState;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isrunning
        {
            get
            {
                return _isrunning;
            }
            set
            {
                OnisrunningChanging(value);
                ReportPropertyChanging("isrunning");
                _isrunning = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isrunning");
                OnisrunningChanged();
            }
        }
        private global::System.Boolean _isrunning;
        partial void OnisrunningChanging(global::System.Boolean value);
        partial void OnisrunningChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean waitingforfiles
        {
            get
            {
                return _waitingforfiles;
            }
            set
            {
                OnwaitingforfilesChanging(value);
                ReportPropertyChanging("waitingforfiles");
                _waitingforfiles = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("waitingforfiles");
                OnwaitingforfilesChanged();
            }
        }
        private global::System.Boolean _waitingforfiles;
        partial void OnwaitingforfilesChanging(global::System.Boolean value);
        partial void OnwaitingforfilesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean processignbatch
        {
            get
            {
                return _processignbatch;
            }
            set
            {
                OnprocessignbatchChanging(value);
                ReportPropertyChanging("processignbatch");
                _processignbatch = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("processignbatch");
                OnprocessignbatchChanged();
            }
        }
        private global::System.Boolean _processignbatch;
        partial void OnprocessignbatchChanging(global::System.Boolean value);
        partial void OnprocessignbatchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 batchId
        {
            get
            {
                return _batchId;
            }
            set
            {
                OnbatchIdChanging(value);
                ReportPropertyChanging("batchId");
                _batchId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("batchId");
                OnbatchIdChanged();
            }
        }
        private global::System.Int32 _batchId;
        partial void OnbatchIdChanging(global::System.Int32 value);
        partial void OnbatchIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 fileid
        {
            get
            {
                return _fileid;
            }
            set
            {
                OnfileidChanging(value);
                ReportPropertyChanging("fileid");
                _fileid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fileid");
                OnfileidChanged();
            }
        }
        private global::System.Int32 _fileid;
        partial void OnfileidChanging(global::System.Int32 value);
        partial void OnfileidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> time
        {
            get
            {
                return _time;
            }
            set
            {
                OntimeChanging(value);
                ReportPropertyChanging("time");
                _time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("time");
                OntimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _time;
        partial void OntimeChanging(Nullable<global::System.DateTime> value);
        partial void OntimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String currentState
        {
            get
            {
                return _currentState;
            }
            set
            {
                OncurrentStateChanging(value);
                ReportPropertyChanging("currentState");
                _currentState = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("currentState");
                OncurrentStateChanged();
            }
        }
        private global::System.String _currentState;
        partial void OncurrentStateChanging(global::System.String value);
        partial void OncurrentStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> isNotLoggedIn
        {
            get
            {
                return _isNotLoggedIn;
            }
            set
            {
                OnisNotLoggedInChanging(value);
                ReportPropertyChanging("isNotLoggedIn");
                _isNotLoggedIn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isNotLoggedIn");
                OnisNotLoggedInChanged();
            }
        }
        private Nullable<global::System.Boolean> _isNotLoggedIn;
        partial void OnisNotLoggedInChanging(Nullable<global::System.Boolean> value);
        partial void OnisNotLoggedInChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> isNotWebURLWorking
        {
            get
            {
                return _isNotWebURLWorking;
            }
            set
            {
                OnisNotWebURLWorkingChanging(value);
                ReportPropertyChanging("isNotWebURLWorking");
                _isNotWebURLWorking = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isNotWebURLWorking");
                OnisNotWebURLWorkingChanged();
            }
        }
        private Nullable<global::System.Boolean> _isNotWebURLWorking;
        partial void OnisNotWebURLWorkingChanging(Nullable<global::System.Boolean> value);
        partial void OnisNotWebURLWorkingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> isNotFolderPathCorrect
        {
            get
            {
                return _isNotFolderPathCorrect;
            }
            set
            {
                OnisNotFolderPathCorrectChanging(value);
                ReportPropertyChanging("isNotFolderPathCorrect");
                _isNotFolderPathCorrect = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isNotFolderPathCorrect");
                OnisNotFolderPathCorrectChanged();
            }
        }
        private Nullable<global::System.Boolean> _isNotFolderPathCorrect;
        partial void OnisNotFolderPathCorrectChanging(Nullable<global::System.Boolean> value);
        partial void OnisNotFolderPathCorrectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> isHalted
        {
            get
            {
                return _isHalted;
            }
            set
            {
                OnisHaltedChanging(value);
                ReportPropertyChanging("isHalted");
                _isHalted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isHalted");
                OnisHaltedChanged();
            }
        }
        private Nullable<global::System.Boolean> _isHalted;
        partial void OnisHaltedChanging(Nullable<global::System.Boolean> value);
        partial void OnisHaltedChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EnableVue_DBModel", Name="Setting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Setting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Setting object.
        /// </summary>
        /// <param name="weburl">Initial value of the weburl property.</param>
        /// <param name="folderpath">Initial value of the folderpath property.</param>
        /// <param name="id">Initial value of the id property.</param>
        public static Setting CreateSetting(global::System.String weburl, global::System.String folderpath, global::System.Int32 id)
        {
            Setting setting = new Setting();
            setting.weburl = weburl;
            setting.folderpath = folderpath;
            setting.id = id;
            return setting;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String weburl
        {
            get
            {
                return _weburl;
            }
            set
            {
                OnweburlChanging(value);
                ReportPropertyChanging("weburl");
                _weburl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("weburl");
                OnweburlChanged();
            }
        }
        private global::System.String _weburl;
        partial void OnweburlChanging(global::System.String value);
        partial void OnweburlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String folderpath
        {
            get
            {
                return _folderpath;
            }
            set
            {
                OnfolderpathChanging(value);
                ReportPropertyChanging("folderpath");
                _folderpath = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("folderpath");
                OnfolderpathChanged();
            }
        }
        private global::System.String _folderpath;
        partial void OnfolderpathChanging(global::System.String value);
        partial void OnfolderpathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EnableVue_DBModel", Name="SimpleLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SimpleLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SimpleLog object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static SimpleLog CreateSimpleLog(global::System.Int32 id)
        {
            SimpleLog simpleLog = new SimpleLog();
            simpleLog.id = id;
            return simpleLog;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String log
        {
            get
            {
                return _log;
            }
            set
            {
                OnlogChanging(value);
                ReportPropertyChanging("log");
                _log = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("log");
                OnlogChanged();
            }
        }
        private global::System.String _log;
        partial void OnlogChanging(global::System.String value);
        partial void OnlogChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> time
        {
            get
            {
                return _time;
            }
            set
            {
                OntimeChanging(value);
                ReportPropertyChanging("time");
                _time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("time");
                OntimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _time;
        partial void OntimeChanging(Nullable<global::System.DateTime> value);
        partial void OntimeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EnableVue_DBModel", Name="UserToken")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserToken : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserToken object.
        /// </summary>
        /// <param name="username">Initial value of the username property.</param>
        /// <param name="password">Initial value of the password property.</param>
        /// <param name="user_id">Initial value of the user_id property.</param>
        /// <param name="last_used">Initial value of the last_used property.</param>
        public static UserToken CreateUserToken(global::System.String username, global::System.String password, global::System.Int32 user_id, global::System.Boolean last_used)
        {
            UserToken userToken = new UserToken();
            userToken.username = username;
            userToken.password = password;
            userToken.user_id = user_id;
            userToken.last_used = last_used;
            return userToken;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String token
        {
            get
            {
                return _token;
            }
            set
            {
                OntokenChanging(value);
                ReportPropertyChanging("token");
                _token = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("token");
                OntokenChanged();
            }
        }
        private global::System.String _token;
        partial void OntokenChanging(global::System.String value);
        partial void OntokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                if (_user_id != value)
                {
                    Onuser_idChanging(value);
                    ReportPropertyChanging("user_id");
                    _user_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("user_id");
                    Onuser_idChanged();
                }
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_saved
        {
            get
            {
                return _is_saved;
            }
            set
            {
                Onis_savedChanging(value);
                ReportPropertyChanging("is_saved");
                _is_saved = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_saved");
                Onis_savedChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_saved;
        partial void Onis_savedChanging(Nullable<global::System.Boolean> value);
        partial void Onis_savedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean last_used
        {
            get
            {
                return _last_used;
            }
            set
            {
                Onlast_usedChanging(value);
                ReportPropertyChanging("last_used");
                _last_used = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("last_used");
                Onlast_usedChanged();
            }
        }
        private global::System.Boolean _last_used;
        partial void Onlast_usedChanging(global::System.Boolean value);
        partial void Onlast_usedChanged();

        #endregion

    
    }

    #endregion

    
}
